### ISSUE TITLE
既往不恋-Daniel

### ISSUE THREAD

**Issue by deusyu** [Doradx/hexo-friendly-links#36]
### 检查清单

- [X] 合法的、非营利性、无商业广告、无木马植入。
- [X] 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，且至少稳定运行半年。
- [X] 无违反国家相关法律法规和道德底线的内容，不涉反动言论和政治敏感话题。
- [X] 与 **博主** 有至少 2 次有效互动（有内容的留言或者 issue 等）。

### 博客名称

既往不恋

### 博客地址

https://deusyu.app/

### 博客图标

https://deusyu.app/img/avatar-2023.png

### 博客描述

Beauty will save the world.

### 友链地址

https://deusyu.app/link/

### 订阅地址

https://deusyu.app/atom.xml

**Comment by Doradx** [comment]
没添加本站友链哦🥹

**Comment by deusyu** [comment]
这个还在搞，搞完添加上，用的你的方案，tg我是Rainman

Dorad ***@***.***> 于 2024年1月30日周二 08:31写道：

**Comment by deusyu** [comment]
已经添加了https://deusyu.app/link/
另外你的isssue是怎么检查是否需要添加上呢，权限控制在哪里呢

**Comment by Doradx** [comment]
在labels控制
